FORMAT: 1A
HOST: http://ebu-storyboard-app.apiblueprint.org

# EBU Storyboard

## Important Info
- Minden http request `Content-type: application/json`-t küld és fogad, kivéve, ha mást írunk lentebb
- Minden API endpoint standard http headerekkel és http hibakódokkal dolgozik
- Ha a kliensnek van auth tokene (azaz “be van jelentkezve”), akkor minden további http requesthez csatolnia kell egy `Authorization: Bearer <auth token>` headert

# Auth endpoints

## Login with email and password [GET /auth/login]
User accounts have to be created manually using the Artisan CLI.

+ Request (application/json)

    + Body
    
            {
                "email": "example@gmail.com",
                "password": "foo123"
            }
            
+ Response 200 (application/json)

    + Body
    
            {
                "token": "myJwtToken"
            }

## Storyboard Folders [/storyboard_folder{?folder_id}]

+ Parameters
    + folder_id (optional) - Filter the list for a parent Folder's `id` field

### List [GET]

+ Response 200 (application/json)

    + Attributes(StoryboardFolderPager)
    
### Create [POST]

+ Request (application/json)

    + Body
    
            {
                "title": "My Folder",
                "folder": {
                    "id": 23,
                }
            }

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
+ Request (application/json)

    + Body
    
            {
                "title": "My Folder",
            }

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
### Show [GET /storyboard_folder/{id}]

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
### Edit [PUT /storyboard_folder/{id}]

+ Request (application/json)

    + Body
    
            {
                "title": "My Folder 3"
            }

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
    
### Delete [DELETE /storyboard_folder/{id}]

+ Request (application/json)

    + Body
    
            {
                
            }

+ Response 200 (application/json)

    + Body
    
            {
            
            }

## Media Folders [/media_folder{?folder_id}]

+ Parameters
    + folder_id (optional) - Filter the list for a parent Folder's `id` field

### List [GET]

+ Response 200 (application/json)

    + Attributes(StoryboardFolderPager)
    
### Create [POST]

+ Request (application/json)

    + Body
    
            {
                "title": "My Folder",
                "folder": {
                    "id": 23,
                }
            }

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
+ Request (application/json)

    + Body
    
            {
                "title": "My Folder",
            }

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
### Show [GET /media_folder/{id}]

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
### Edit [PUT /media_folder/{id}]

+ Request (application/json)

    + Body
    
            {
                "title": "My Folder 3"
            }

+ Response 200 (application/json)

    + Attributes(StoryboardFolder)
    
    
### Delete [DELETE /media_folder/{id}]

+ Request (application/json)

    + Body
    
            {
                
            }

+ Response 200 (application/json)

    + Body
    
            {
            
            }


## STORYBOARD [/storyboard]
Storyboard related endpoints

### List [GET]
Get the storyboard list

+ Response 200 (application/json)

    + Attributes(StoryboardPager)
    
### Create [POST]
Create new storyboard

+ Request (application/json)

    + Body
    
            {
                "title": "My Awesome Storyboard",
                "aspect_ratio": "16by9"
            }

+ Response 200 (application/json)

    + Attributes(Storyboard)

## STORYBOARD Details [/storyboard/{id}]
Storyboard Details related endpoints

+ Parameters
    + id (required, number, `1`) - Storyboard ID or current

### Show [GET]
Get a storyboard by ID

+ Response 200 (application/json)

    + Attributes(Storyboard)
    
### Edit [PUT]
Edit storyboard

+ Request (application/json)

    + Body
    
            {
                "title": "My Awesome Storyboard"
            }

+ Response 200 (application/json)

    + Attributes(Storyboard)


# Data Structures

## Pager

+ total: 4 (number)
+ per_page: 15 (number)
+ current_page: 1 (number)
+ last_page: 1 (number)
+ from: 1 (number)
+ to: 2 (number)

## Storyboard (object)
+ id: 11212 (number)
+ title: `Teszt` (string)
+ aspect_ratio: `16by9` (string)
+ cover_image
    + Include ImageThumbnail
+ `last_video_export`
    + Include ConvertedVideo
+ timeline
    + Include StoryboardTimeline
+ user
    + Include User
+ created_at: `2017-03-12T12:12:12` (string)

## StoryboardTemplate (object)
+ Include Storyboard

## StoryboardFolder (object)
+ id: 12 (number)
+ title: `My Folder` (string)
+ folder: null
+ created_at: `2017-03-12 12:12:12` (string)

## StoryboardFolderPager (object)
+ Include Pager
+ data: StoryboardFolder, StoryboardFolder (array[StoryboardFolder])

## StoryboardTimeline (object)
+ id: 11212 (number)


## StoryboardPager (object)
+ Include Pager
+ data: Storyboard, Storyboard (array[Storyboard])

## ImageThumbnail (object)
+ id: 12 (number)
+ sizes (object)
    + small
        + Include ThumbnailSize
    + medium
        + Include ThumbnailSize
    + large
        + Include ThumbnailSize
+ is_placeholder: false

## ThumbnailSize (object)
+ url: `http://example.org/images/123.png` (string)
+ width: 0 (number)
+ height: 0 (number)

## ConvertedVideo (object)
+ id: 12 (number)
+ convertation
    + pending: true (boolean)
    + completed: false (boolean)
    + successful: false (boolean)
    + failed: false (boolean)
+ thumbnail
    + Include ImageThumbnail
+ sources: ConvertedVideoSource, ConvertedVideoSource (array[ConvertedVideoSource])
+ resolution
    + width: 0 (number)
    + height: 0 (number)
+ created_at: `2017-03-12 12:12:12` (string)

## ConvertedVideoSource (object)
+ url: `http://example.org/video.mp4` (string)
+ mime_type: `video/mp4`
+ size: 1515 (number)

## StoryboardTemplatePager (object)
+ Include Pager
+ data: StoryboardTemplate, StoryboardTemplate (array[StoryboardTemplate])


## User (object)

+ id: 11212 (number)
+ first_name: `Teszt` (string)
+ last_name: `Elek` (string)
+ email: `elek.teszt@example.org` (string)