## TEMPLATE [/template]

### List [GET]

+ Response 200 (application/json)

    + Attributes(TemplatePager)

## TEMPLATE Details [/template/{id}]

+ Parameters
    + id (required, number, `1`) - Template ID or current

### Show [GET]

+ Response 200 (application/json)

    + Attributes(Template)
